routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Pages Controller
Route::get('/', 'PageController@index')->name('home');
Route::get('/aboutme', 'PageController@aboutMe')->name('about-me');
Route::get('/hireme', 'PageController@hireMe')->name('hireme');
Route::get('/portfolio', 'PageController@portfolios')->name('portfolios');

// Admin Routes
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::view('/' , 'admin.home')->name('adminhome');
    Route::resource('portfolio' , 'PortfolioController');
    Route::resource('category' , 'CategoryController');
    Route::resource('companylogo' , 'CompanyLogoController');
    Route::resource('slider' , 'SliderController');
    Route::resource('testimonial', 'TestimonialController');
});
Route::post('/contactform', 'PageController@ctForm')->name('ctForm');
Auth::routes();

app/Portfolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    protected $fillable = ['title' , 'description' , 'photo' , 'slug' , 'category_id' , 'highligt'];

    public function categories() {
        return $this->belongsTo('App\Category' , 'category_id' , 'id');
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;
use App\Category;
use App\Portfolio;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
class PortfolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
    */
    public function index()
    {
        // $portfolios = Category::with('portfolio')->orderBy('id' , 'DESC')->get();
        $portfolios = Portfolio::with('categories')->orderBy('id' , 'DESC')->get();
        // return dd($portfolios);
        return view('admin.portfolio.home' , [
            'portfolios' => $portfolios
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.portfolio.create' , [
            'categories' => $categories,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all() , [
            'featureimg' => 'required|max:8048',
            'title' => 'required|min:3|max:20',
            'category' => 'required',
        ]);


        if($validator->fails()) {
            return back()->withErrors($validator->errors());
        } else {
            if($file = $request->file('featureimg')) {
                $name = time().time().'.'.$file->getClientOriginalExtension();
                $targetPath = public_path('/uploads/');
                if($file->move($targetPath , $name)) {
                   
                    
                    // Storing to Database
                    $data = [
                        'title' => trim(strtolower($request->title)),
                        'description' => $request->description,
                        'photo' => $name,
                        'slug'  => Str::slug($request->title , '-'),
                        'category_id' => $request->category,
                        'highligt' => ($request->highlight == 'on') ? '1' : '0',
                    ];

                    $save = Portfolio::create($data);
                    if( $save ) {
                        return redirect()->route('portfolio.index')->with('success' , 'Portfolio Added');
                    }
                }
            }

            return back()->with('uploadErr' , 'Error Uploading Images');
        }        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $portfolio = Portfolio::with('categories')->find($id);
        $categories = Category::all();
        return  view('admin.portfolio.edit' ,[
            'portfolio' => $portfolio,
            'categories' => $categories,
        ] );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all() , [
            'featureimg' => 'mimes:jpeg,png,jpg,bmp,mp4,webm,3gp,mov|max:8048',
            'title' => 'required|min:3|max:20',
            'category' => 'required|'

        ]);

        if($validator->fails()) {
            return back()->withErrors($validator->errors());
        } else {
            $portfolioSave              = Portfolio::find($id);
            $portfolioSave->title       = trim(strtolower($request->title));
            $portfolioSave->description = $request->description;
            $portfolioSave->highligt = ($request->highlight == 'on') ? '1' : '0';


            $portfolioSave->category_id = $request->category;
            $portfolioSave->slug        = Str::slug($request->title , '-');

            if($file = $request->file('featureimg')) {
                $name = time().time().'.'.$file->getClientOriginalExtension();
                $targetPath = public_path('/uploads/'); 
                $portfolioSave->photo = $name;
                $file->move($targetPath , $name);
            }  

            if( $portfolioSave->save() ) {
                return redirect()->route('portfolio.index')->with('success' , 'Portfolio Updated');
            }

            return back()->with('uploadErr' , 'Error Uploading Images');
        }        
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        $delte = Portfolio::find($id);
        $delte->delete();
        if($delte) {
        return redirect()->route('portfolio.index')->with('success' , 'Portfolio Deleted Successfully');
        }
        return redirect()->route('portfolio.index')->with('errdel' , 'Error Deleting. Please try again');
    }

}

resources/views/admin/portfolio/create.blade.php
@extends('layout-admin')
@section('title')
Dashboard
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Portfolio</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('category.index')}}">Category List</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 m-auto">
            @if ($fs = Session::get('uploadErr'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">Add Porfolio</div>
                <div class="card-body">
                    <form action="{{route('portfolio.store')}}" method="post" enctype="multipart/form-data" >
                        @csrf
                        <div class="form-group">
                            <label for="title">Title*</label>
                            <input type="text" name="title" placeholder="Title" 
                            class="form-control" id="title" value="{{old('title')}}">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea name="description" placeholder="Description" 
                            class="form-control" id="description" cols="30" rows="5">
                        </textarea>
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select name="category" id="category"   class="form-control">
                                <option value="" >Select Category</option>
                                @if(!$categories->isEmpty())
                                    @foreach ($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                       <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="featureimg">FeatureImg</label>
                                    <input type="file" name="featureimg" class="" id="featureimg">
                                    <p class="small">Upload Jpeg, Jpg, Png, Gif and .mp4 only less than 8 mb </p>
                                </div>
                                <div class="col-md-6">
                                    <label for="extraimg">Extra Images</label>
                                    <input type="file" name="extraimages[]" class="" id="extraimg">
                                    <p class="small">Upload Jpeg, Jpg, Png only less than 8 mb </p>
                                </div>
                            </div>
                       </div>
                       <div class="form-group">
                        <label for="highlight">Highlight</label>
                        <input type="checkbox" name="highlight"  class="checkbox-light" >
                       </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/portfolio/edit.blade.php
@extends('layout-admin')
@section('title')
Dashboard
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit Portfolio</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('portfolio.index')}}">Portfolio List</a>
            <a class="btn btn-outline-info" href="{{route('portfolio.create')}}">Add Portfolio</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 m-auto">
            @if ($fs = Session::get('uploadErr'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">Add Porfolio</div>
                <div class="card-body">
                    <form action="{{route('portfolio.update' , $portfolio->id)}}" method="post" enctype="multipart/form-data" >
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="title">Title*</label>
                            <input type="text" name="title" placeholder="Title" 
                            class="form-control" id="title" value="{{$portfolio->title}}">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea name="description" placeholder="Description" 
                            class="form-control" id="description" cols="30" rows="5">{{$portfolio->description}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select name="category" id="category"   class="form-control">
                                <option value="" >Select Category</option>
                                @if(!$categories->isEmpty())
                                    @foreach ($categories->toArray() as $category)
                                        <option value="{{$category['id']}}" @if(in_array($portfolio->categories->name , $category)) selected @endif >{{$category['name']}}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                       <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="featureimg">FeatureImg</label>
                                    <input type="file" name="featureimg" class="" id="featureimg">
                                    <p class="small">Upload Jpeg, Jpg, Png, Gif and .mp4 only less than 2 mb </p>
                                    <img src="/uploads/{{$portfolio->photo}}" alt="" class="img-fluid img-thumbnail" width="120px">
                                </div>
                                <div class="col-md-6">
                                    <label for="extraimg">Extra Images</label>
                                    <input type="file" name="extraimages[]" class="" id="extraimg">
                                    <p class="small">Upload Jpeg, Jpg, Png only less than 2 mb </p>
                                </div>
                            </div>
                       </div>
                       <div class="form-group">
                            <label for="highlight">Highlight</label>
                            @if($portfolio->highligt == '0') 
                            <input type="checkbox" name="highlight"  class="checkbox-light" >
                            @endif
                            @if($portfolio->highligt == '1') 
                            <input type="checkbox" name="highlight" checked  class="checkbox-light" >
                            @endif
                       </div>
                       
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/portfolio/home.blade.php
@extends('layout-admin')
@section('title')
Dashboard
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Profile</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('portfolio.create')}}">Add Portfolio</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @if ($fs = Session::get('success'))
                <div class="alert alert-success">
                    {{ $fs}}
                </div>
            @endif
            @if ($fs = Session::get('errdel'))
            <div class="alert alert-danger">
                {{ $fs}}
            </div>
        @endif
            <div class="card">
                <div class="card-header">
                    Portfolio Lists
                </div>
                <div class="card-body">
                    <table class="table table-sm table-bordered">
                        <thead>
                            <tr>
                            <th>#</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Highlight</th>
                            <th>Created At</th>
                            <th>Updated At</th>
                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (!$portfolios->isEmpty())
                                @foreach ($portfolios as $portfolio)    
                                <tr>
                                    <td>{{$portfolio->id}}</td>
                                    <td>
                                        <img src="/uploads/{{$portfolio->photo}}" alt="{{ucfirst($portfolio->title)}}" class="img-fluid img-thumbnail" width="80px">
                                    </td>
                                    <td>{{ucfirst($portfolio->title)}}</td>
                                    <td>{{ ucfirst($portfolio->categories->name) }}</td>
                                    <td>
                                        @if($portfolio->highligt == '1')
                                        <button class="btn btn-sm btn-success">Yes</button>
                                        @endif
                                        @if($portfolio->highligt == '0')
                                        <button class="btn btn-sm btn-success">No</button>
                                        @endif
                                    </td>
                                    <td>{{$portfolio->created_at}}</td>
                                    <td>{{$portfolio->updated_at}}</td>
                                    <td>
                                        <div class="btn-group-sm">
                                            <a href="{{route('portfolio.edit' , $portfolio->id)}}" role="button" class="btn btn-sm btn-info d-inline">Edit</a>
                                            <form class="d-inline" method="post" action="{{route('portfolio.destroy' , $portfolio->id)}}">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-danger">Del</button>
                                            </form>
                                        </div>
                                    </td>
                                    
                                </tr>
                                @endforeach   
                            @else
                                <tr><td colspan="12" class="text-center">
                                    <p>No Result Found</p>
                                    <a class="btn btn-outline-info" href="{{route('portfolio.create')}}">Add Portfolio</a>
                                    </td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection