routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Pages Controller
Route::get('/', 'PageController@index')->name('home');
Route::get('/aboutme', 'PageController@aboutMe')->name('about-me');
Route::get('/hireme', 'PageController@hireMe')->name('hireme');
Route::get('/portfolio', 'PageController@portfolios')->name('portfolios');

// Admin Routes
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::view('/' , 'admin.home')->name('adminhome');
    Route::resource('portfolio' , 'PortfolioController');
    Route::resource('category' , 'CategoryController');
    Route::resource('companylogo' , 'CompanyLogoController');
    Route::resource('slider' , 'SliderController');
    Route::resource('testimonial', 'TestimonialController');
});
Route::post('/contactform', 'PageController@ctForm')->name('ctForm');
Auth::routes();

app/Category.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use App\Portfolio;
class Category extends Model
{
    protected $fillable = ['name' , 'slug'];


    public function portfolio() {
        return $this->hasMany('App\Portfolio' , 'category_id' , 'id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Str;
use App\Category;
use Illuminate\Http\Request;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id' , 'DESC')->get();
        return view('admin.category.home' , [
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Checking if the same name is available
        $name = Category::where('name' , '=' ,strtolower($request->name))->first();

        if($name === null) {

            $valiate = $request->validate([
                'name' => ['required' , 'max:50' , 'min:2' , ],
            ]);
    
            if($valiate) {
                
                $data = [
                    'name' => strtolower($request->name),
                    'slug' =>  Str::slug($request->name , '-'),     
                ];
                $category = Category::create($data);
                if($category) {
                    $request->session()->flash('success' , 'Successfully Created');
                } else {
                    $request->session()->flash('error' , 'Problem saving category');
                }
            }
        } 

        if($name !== null) {
            $request->session()->flash('exists' , 'Already exists');
        }
        
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categories = Category::orderBy('id' , 'DESC')->get();
        $categoryData = Category::find($id);
        return view('admin.category.home' , [
            'categories' => $categories,
            'categorydata' => $categoryData,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editData = Category::find($id);
        return view('admin.category.edit' , [
            'editData' => $editData,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
        $validate = $request->validate([
            'name' => ['required' , 'max:50' , 'min:2' , ],
        ]);

        $editData = Category::find($id);

        $editData->name = strtolower($request->name);
        $editData->slug = Str::slug($request->name , '-');
        
        $save = $editData->save();

        if($save) {
            return redirect()->route('category.index')->with('categoryupdated' , 'Successfully Updated');
        } 
       
        return $request->session()->flash('errorupdating' , 'Problem updating category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id)->delete();
        return redirect()->route('category.index')->with('categorydeleted' , 'Successfully Deleted');
    }
}

resources/views/admin/category/create.blade.php
@extends('layout-admin')
@section('title')
Add Category
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Category</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('category.index')}}">Category List</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 m-auto">
           
            @if ($fs = Session::get('exists'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($fs = Session::get('wrong'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">Create Category</div>
                <div class="card-body">
                    <form action="{{route('category.store')}}" method="post" >
                        @csrf
                        <div class="form-group">
                            <label for="categoryname">Category Name*</label>
                            <input type="text"  name="name" placeholder="Category Name" 
                            class="form-control" 
                            id="categoryname" value="@if(isset($categorydata)) {{$categorydata->name}} @endif">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/category/edit.blade.php
@extends('layout-admin')
@section('title')
Edit Category
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Category</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('category.index')}}">Category List</a>
            <a class="btn btn-outline-info" href="{{route('category.create')}}">Add Category</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 m-auto">
           
            @if ($fs = Session::get('exists'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($fs = Session::get('wrong'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">Edit Category</div>
                <div class="card-body">
                    <form action="{{route('category.update' , $editData->id)}}" method="POST" >
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="categoryname">Category Name*</label>
                            <input type="text"  name="name" placeholder="Category Name" 
                            class="form-control" 
                            id="categoryname" value="@if(isset($editData)){{$editData->name}}@endif">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/category/home.blade.php
@extends('layout-admin')
@section('title')
Category
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Category</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('category.create')}}">Add Category</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Category Lists
                </div>
                <div class="card-body">
                    @if ($fs = Session::get('success'))
                        <div class="alert alert-success">
                            {{ $fs}}
                        </div>
                    @endif
                    @if ($fs = Session::get('categorydeleted'))
                        <div class="alert alert-success">
                            {{ $fs}}
                        </div>
                    @endif
                    @if ($categories->isEmpty())
                        <div>
                            <a class="btn btn-outline-info" href="{{route('category.create')}}">Add Category</a>
                        </div>
                    @else
                        <div class="table-responsive">
                            <table class="table table-sm table-bordered">
                                <thead>
                                    <tr>
                                    <th>#</th>
                                    <th>Category Name</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($categories as $category)    
                                    <tr>
                                        <td>{{$category->id}}</td>
                                        <td>{{$category->name}}</td>
                                        <td>{{$category->created_at}}</td>
                                        <td>{{$category->updated_at}}</td>
                                        <td>
                                            <div class="btn-group-sm d-inline">
                                                <a href="{{route('category.edit' , $category->id)}}" role="button" class="btn btn-sm btn-info">Edit</a>
                                                <form method="post" class="d-inline" action="{{route('category.destroy' , $category->id)}}">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</main>
@endsection