routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Pages Controller
Route::get('/', 'PageController@index')->name('home');
Route::get('/aboutme', 'PageController@aboutMe')->name('about-me');
Route::get('/hireme', 'PageController@hireMe')->name('hireme');
Route::get('/portfolio', 'PageController@portfolios')->name('portfolios');

// Admin Routes
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::view('/' , 'admin.home')->name('adminhome');
    Route::resource('portfolio' , 'PortfolioController');
    Route::resource('category' , 'CategoryController');
    Route::resource('companylogo' , 'CompanyLogoController');
    Route::resource('slider' , 'SliderController');
    Route::resource('testimonial', 'TestimonialController');
});
Route::post('/contactform', 'PageController@ctForm')->name('ctForm');
Auth::routes();

resources/views/admin/logowork/create.blade.php
@extends('layout-admin')
@section('title')
Add Logo
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Logo</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('companylogo.index')}}">Logo List</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 m-auto">
            @if ($fs = Session::get('uploadErr'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">Add Logo</div>
                <div class="card-body">
                    <form action="{{route('companylogo.store')}}" method="post" enctype="multipart/form-data" >
                        @csrf
                        <div class="form-group">
                            <label for="title">Title*</label>
                            <input type="text" name="title" placeholder="Title" 
                            class="form-control" id="title" value="">
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select name="category" id="category" class="form-control">
                                <option value="">Select Types</option>
                                <option value="brand">Brand</option>
                                <option value="company">Company</option>
                            </select>
                        </div>
                       <div class="form-group">
                        <label for="logoimg">Logo Image</label>
                        <input type="file" name="logoimg" class="" id="logoimg">
                        <p class="small">Upload Jpeg, Jpg, Png only less than 2 mb </p>
                       </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/logowork/edit.blade.php
@extends('layout-admin')
@section('title')
Edit Logo
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit Logo</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('companylogo.index')}}">Logo List</a>
            <a class="btn btn-outline-info" href="{{route('companylogo.create')}}">Add Logo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 m-auto">
            @if ($fs = Session::get('uploadErr'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">Add Logo</div>
                <div class="card-body">
                    <form action="{{route('companylogo.update' , $logo->id)}}" method="post" enctype="multipart/form-data" >
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="title">Title*</label>
                            <input type="text" name="title" placeholder="Title" 
                            class="form-control" id="title" value="{{$logo->title}}">
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select name="category" id="category" class="form-control">
                                <option value="">Select Types</option>
                                <option value="brand" @if($logo->category == 'brand' ) selected @endif>Brand</option>
                                <option @if($logo->category == 'company' ) selected @endif value="company">Company</option>
                            </select>
                        </div>
                       <div class="form-group">
                        <label for="logoimg">Logo Image</label>
                        <input type="file" name="logoimg" class="" id="logoimg">
                        <p class="small">Upload Jpeg, Jpg, Png only less than 2 mb </p>
                        <img src="/uploads/logos/{{$logo->company_logo}}" class="img-fluid img-thumbnail" width="100px"  alt="">
                       </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/logowork/home.blade.php
@extends('layout-admin')
@section('title')
Brand / Company Logo
@endsection
@section('body')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Brand / Company Logo</h1>
        <div>
            <a class="btn btn-outline-info" href="{{route('companylogo.create')}}">Add Brand / Company Logo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @if ($fs = Session::get('success'))
                <div class="alert alert-success">
                    {{ $fs}}
                </div>
            @endif
            @if ($fs = Session::get('errdel'))
                <div class="alert alert-danger">
                    {{ $fs}}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Brand / Comapny Logo 
                </div>
                <div class="card-body">
                    <table class="table table-sm table-bordered">
                        <thead>
                            <tr>
                            <th>#</th>
                            <th>Logo Image</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Created At</th>
                            <th>Updated At</th>
                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (!$logos->isEmpty())
                                @foreach ($logos as $logo)    
                                <tr>
                                    <td>{{$logo->id}}</td>
                                    <td>
                                        <img src="/uploads/logos/{{$logo->company_logo}}" alt="{{ucfirst($logo->title)}}" class="img-fluid img-thumbnail" width="80px">
                                    </td>
                                    <td>{{ucfirst($logo->title)}}</td>
                                    <td>
                                        @if($logo->category == 'brand')
                                        <button class="btn btn-sm btn-success">Brand</button>
                                        @endif
                                        @if($logo->category == 'company')
                                        <button class="btn btn-sm btn-success">Company</button>
                                        @endif
                                    </td>
                                    <td>{{$logo->created_at}}</td>
                                    <td>{{$logo->updated_at}}</td>
                                    <td>
                                        <div class="btn-group-sm">
                                            <a href="{{route('companylogo.edit' , $logo->id)}}" role="button" class="btn btn-sm btn-info d-inline">Edit</a>
                                            <form class="d-inline" method="post" action="{{route('companylogo.destroy' , $logo->id)}}">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-danger">Del</button>
                                            </form>
                                        </div>
                                    </td>
                                    
                                </tr>
                                @endforeach   
                            @else
                                <tr><td colspan="12" class="text-center">
                                    <p>No Result Found</p>
                                    <a class="btn btn-outline-info" href="{{route('companylogo.create')}}">Add Logo</a>
                                    </td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection